### ISSUE TITLE
Zoom client app should not be uninstalled

### ISSUE THREAD

**Issue by felideon** [ryanfb/deZoom#1]
My reading of the [original blog post](https://medium.com/@jonathan.leitschuh/zoom-zero-day-4-million-webcams-maybe-an-rce-just-get-them-to-visit-your-website-ac75c83f4ef5) was that the patch consists of:

1. Disabling the default video setting.
2. Removing the local web server.

It does not say you should uninstall the Zoom app completely. In fact, a [comment in the gist](https://gist.github.com/JLLeitschuh/e2550ddd8d6dfd94447b0b557891ba30#file-permanent_zoom_and_ringcentral_server_remover-sh-L2) mentions the Zoom functionality should not be impacted.

**Comment by ryanfb** [comment]
The goal of this is to completely remove Zoom, so that users can reinstall the latest version later if they wish. Many people are running outdated versions of Zoom which are also affected by the DOS vulnerability discussed in the blog post, to quote:

> Additionally, due to a lack of sufficient auto-update capabilities, many users continue to run outdated versions of Zoom for months after new releases are shipped leaving them vulnerable to exploits like these.

After completely removing Zoom, a user should be able to reinstall with the latest version, and since the `~/.zoomus`and `~/.ringcentralopener` directories are blocked, the other vulnerable processes shouldn't be reinstalled alongside it.

**Comment by felideon** [comment]
That makes sense. I just updated Zoom from within their client app and then applied the matches. It was just this line that threw me off, since removing the client app was not explicitly in the recommendation:

> This is the course of action recommended in the vulnerability disclosure. 

Though implicitly, yes, you should update the client app.
